---
book_repo: pivotal-cf/docs-book-telmetry
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'edge'

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

elastic_search: true

public_host: docs.pivotal.io

feedback_enabled: true

sections:
- repository:
    name: pivotal-cf/docs-telemetry
    ref: '1.1'
  directory: telemetry/1-1
  subnav_template: telemetry_1_1.erb
  product_info:
    use_local_header: true
    latest_stable_version: '01.0'
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Telemetry Collector
    search_placeholder: Search Telemetry Collector 1.1
    url_prefix: telemetry/1-1
    local_product_version: 1.1
    local_header_links: []
    local_header_version_list:
      - url_prefix: https://docs.pivotal.io/telemetry/1-0
        display_name: v1.1
      
