---
book_repo: pivotal-cf/docs-book-telmetry
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'master'

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

elastic_search: true

public_host: docs.pivotal.io

feedback_enabled: true

sections:
- repository:
    name: pivotal-cf/docs-telemetry
    ref: '1.1'
  directory: telemetry/1-1
  subnav_template: telemetry_1_1.erb
  product_info:
    use_local_header: true
    latest_stable_version: '1.1'
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Telemetry Collector
    search_placeholder: Search Telemetry Collector 1.1
    url_prefix: telemetry/1-1
    local_product_version: 1.1
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/telemetry/1-0
        display_name: v1.0
      - url_prefix: http://docs.pivotal.io/telemetry/0-7
        display_name: v0.7
      - url_prefix: http://docs.pivotal.io/telemetry/0-6
        display_name: v0.6
      - url_prefix: http://docs.pivotal.io/telemetry/0-5
        display_name: v0.5
- repository:
    name: pivotal-cf/docs-telemetry
    ref: '1.0'
  directory: telemetry/1-0
  subnav_template: telemetry_1_0.erb
  product_info:
    use_local_header: true
    latest_stable_version: '1.0'
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Telemetry Collector
    search_placeholder: Search Telemetry Collector 1.0
    url_prefix: telemetry/1-0
    local_product_version: 1.0
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/telemetry/1-1
        display_name: v1.1
      - url_prefix: http://docs.pivotal.io/telemetry/0-7
        display_name: v0.7
      - url_prefix: http://docs.pivotal.io/telemetry/0-6
        display_name: v0.6
      - url_prefix: http://docs.pivotal.io/telemetry/0-5
        display_name: v0.5
- repository:
    name: pivotal-cf/docs-telemetry
    ref: '0.7'
  directory: telemetry/0-7
  subnav_template: telemetry_0_7.erb
  product_info:
    use_local_header: true
    latest_stable_version: '0.7'
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Telemetry Collector
    search_placeholder: Search Telemetry Collector 0.7
    url_prefix: telemetry/0-7
    local_product_version: 0.7
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/telemetry/1-1
        display_name: v1.1
      - url_prefix: http://docs.pivotal.io/telemetry/1-0
        display_name: v1.0
      - url_prefix: http://docs.pivotal.io/telemetry/0-6
        display_name: v0.6
      - url_prefix: http://docs.pivotal.io/telemetry/0-5
        display_name: v0.5
- repository:
    name: pivotal-cf/docs-telemetry
    ref: '0.6'
  directory: telemetry/0-6
  subnav_template: telemetry_0_6.erb
  product_info:
    use_local_header: true
    latest_stable_version: '0.6'
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Telemetry Collector
    search_placeholder: Search Telemetry Collector 0.6
    url_prefix: telemetry/0-6
    local_product_version: 0.7
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/telemetry/1-1
        display_name: v1.1
      - url_prefix: http://docs.pivotal.io/telemetry/1-0
        display_name: v1.0
      - url_prefix: http://docs.pivotal.io/telemetry/0-7
        display_name: v0.7
      - url_prefix: http://docs.pivotal.io/telemetry/0-5
        display_name: v0.5
- repository:
    name: pivotal-cf/docs-telemetry
    ref: '0.5'
  directory: telemetry/0-5
  subnav_template: telemetry_0_5.erb
  product_info:
    use_local_header: true
    latest_stable_version: '0.5'
    local_header_img: /images/cloud_rings.png
    local_header_title: Pivotal Telemetry Collector
    search_placeholder: Search Telemetry Collector 0.5
    url_prefix: telemetry/0-5
    local_product_version: 0.7
    local_header_links: []
    local_header_version_list:
      - url_prefix: http://docs.pivotal.io/telemetry/1-1
        display_name: v1.1
      - url_prefix: http://docs.pivotal.io/telemetry/1-0
        display_name: v1.0
      - url_prefix: http://docs.pivotal.io/telemetry/0-7
        display_name: v0.7
      - url_prefix: http://docs.pivotal.io/telemetry/0-6
        display_name: v0.6
